### ISSUE TITLE
Clarify the behaviour upon a new deployment

### ISSUE THREAD

**Issue by danse** [eHealthAfrica/sense-dispatch#17]
This comment https://github.com/eHealthAfrica/sense-dispatch/pull/13#issuecomment-138852414 makes me think about problems we might meet during a new deployment:
1. changes happening _during_ the deployment get processed twice and messages get sent twice
2. changes happening during the deployment get lost and generate no messages
3. **all** changes are duplicated during the deployment and generate new messages

I want to be totally sure that `3` will not happen. Since you mentioned replication, i am afraid that a replication might cause all change events to be evaluated again, thus sending messages for all events happened since the beginning of the database!

Also `2` would be bad, while `1` is annoying but tolerable i think. I am also interested in the solutions @jo adopted in order to avoid similar problems. In general i can hardly answer to these questions without knowing the deployment process in detail, so i involve @skoni in order to help me figuring this out. We can keep this issue as a resource for other components relying on the changes feed

**Comment by danse** [comment]
- @skoni is replication completed _before_ the new service is started?
- @jo will replication trigger new change events?

If you do not know the answers or have no time for this, let me know and i will investigate this

**Comment by jo** [comment]
Sure, when you listen to a database and docs are replicated to it than there will be changes entries for those document revisions. Replication does nothing special, it also inserts the documents via `bulk_docs` api. (the only special thing is the use of `new_edits: false` btw.)

**Comment by tillre** [comment]
As far as i know, the old data is copied over by db-file and would therefor be present before the service is started. Then before the switch from the old to the new container is made, another replication is run to get any documents that would have been added during the deployment process. I dont know how long the process takes, but any document added during that time, would trigger messages on both containers, i think. Maybe @tremolo can shed some more light on the process and add his thoughts.

**Comment by danse** [comment]
Wow, then we risk that `3` could happen! I would say that the solution has to be located in the way the deployment process works, because no component relying on the changes feed can have a way to be robust to this. The service should be launched once replication is completed

**Comment by danse** [comment]
What if the service was in its own deployment process? @jo are sequence numbers persisted upon replication? This way, the service would see its connection dropping, and then it would reconnect to the new database. If the sequence number has been correctly replicated, everything would happen without duplications or omissions

**Comment by tillre** [comment]
I think you cant rely on seq numbers

**Comment by jo** [comment]
Yes, you can't rely on sequence numbers, they differ between databases.

**Comment by danse** [comment]
So as far as i see this, the only way to be robust to new deployments would be:
- having the service deployed separately
- run the service over its own replica of the remote database

I think that the migrator is not deployed separately though, right @jo?

**Comment by jo** [comment]
What I have previously done in the context of an image processing daemon is the following:

When the doc arrives via changes feed, the service _grabs_ the doc by inserting a stemp á la "I am currently processing this document" and saves it. If the save fails, another instance has already grabbed it in the meantime and it can be discarded (it will arrive again via changes feed anyway). The service ignores documents with this stemp. Then, when processing has finished (eg sms was sent) the doc gets updated again, this time with _completed_ mark and, for example, the response of the sms gateway. Documents with such a mark are ignored, too.
That enables good monitoring, you can query all docs which are currently processed, all completed, as well as errored docs, together with their responses.

I implemented this pattern in [General Attachments Worker](https://github.com/jo/worker-attachments#document-status-object).

An improvement of this would be to store the processing information in seperate documents, or even in a different database.

Also maybe of interest here: https://github.com/jo/couch-daemon.

**Comment by danse** [comment]
thanks @jo! i wanted to avoid writing in the database, but at this point this seems the faster approach, allowing us to stick with the current deployment system

**Comment by jo** [comment]
I would generally prefer to design a service in a way that it is idempotent. Thats also how the migrator works.

**Comment by danse** [comment]
good point, but it would be nice to be able to have an idempotent service without the need to write on the database it is following, but not this time :)

**Comment by jo** [comment]
In distributed systems idempotence gets even more important. And since in our case of the distribution object being the database, writing to the very database is the only way to distribute state and to achieve idempotence.

**Comment by danse** [comment]
If the database replications were implemented differently, with deterministic checkpoints for example, we could just rely on the replica, without the need to keep track of our local state in the database to be followed. Or if the database was fully event-based, every event would be identified uniquely and those identifiers would be kept upon replication, then the last identifier would be all the state to be kept in the service, again without the need to modify the source of events

**Comment by jo** [comment]
Maybe :)

But one could argue that post processing information, in our case the sms delivery status, belongs to the document which initiated the processing. Here I think its indeed useful for the client to see the delivery state.

**Comment by tillre** [comment]
Adding that information to the doc has also the advantages mentioned above, that we can track and analyze the messages that have been sent.

**Comment by danse** [comment]
This led to #18
